sudo: true
dist: trusty
language: rust

addons:
  apt:
    sources:
      - sourceline: 'ppa:pinepain/libv8-5.4'
      - ubuntu-toolchain-r-test
    packages:
      # Modern compilers
      - gcc-7
      - g++-7
      # The V8 version that we want to bind
      - libv8-5.4-dev
      - libicu-dev
      # Dependencies for travis-cargo and for coverage
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

matrix:
  include:
    - env: FEATURES="" CC=gcc-7 CXX=g++-7
      rust: stable
      os: linux
    - env: FEATURES="" CC=gcc-7 CXX=g++-7
      rust: nightly
      os: linux
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get install libv8-6.6-dev -y

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH

script:
  - |
      travis-cargo build -- $FEATURES &&
      travis-cargo test -- $FEATURES &&
      travis-cargo bench -- $FEATURES

after_success:
  - |
    echo "SUCCESS"
